### ISSUE TITLE
Error when trying to leave a nonexisting jamsession

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-backend#30]
```
WARN[1474] Error setting client to pause                 JamSession=XFX7Y
2020/10/09 18:26:35 http: panic serving 172.27.0.1:36668: runtime error: index out of range [0] with length 0
goroutine 6339 [running]:
net/http.(*conn).serve.func1(0xc000162960)
        /usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x8b11c0, 0xc000322040)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/jamfactoryapp/jamfactory-backend/controllers.DeleteJamSession(0xc0003d0895, 0x5)
        /go/src/github.com/jamfactoryapp/jamfactory-backend/controllers/jamfactory.go:90 +0x334
github.com/jamfactoryapp/jamfactory-backend/controllers.leaveJamSession(0x98ffa0, 0xc000268540, 0xc000440000)
        /go/src/github.com/jamfactoryapp/jamfactory-backend/controllers/jamsession.go:198 +0x4c2
net/http.HandlerFunc.ServeHTTP(0x9028e0, 0x98ffa0, 0xc000268540, 0xc000440000)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/jamfactoryapp/jamfactory-backend/controllers.(*SessionRequiredMiddleware).Handler.func1(0x98ffa0, 0xc000268540, 0xc000239f00)
        /go/src/github.com/jamfactoryapp/jamfactory-backend/controllers/middlewares.go:68 +0x1c0
net/http.HandlerFunc.ServeHTTP(0xc00009b780, 0x98ffa0, 0xc000268540, 0xc000239f00)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001320c0, 0x98ffa0, 0xc000268540, 0xc000239d00)
        /go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000182000, 0x98ffa0, 0xc000268540, 0xc000239d00)
        /go/pkg/mod/github.com/gorilla/handlers@v1.4.2/cors.go:138 +0x2a6
net/http.serverHandler.ServeHTTP(0xc000184000, 0x98ffa0, 0xc000268540, 0xc000239d00)
        /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000162960, 0x991260, 0xc000345940)
        /usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2962 +0x35c
```

**Comment by exp625** [comment]
Hopefully fixed by the big R
