### ISSUE TITLE
Analyze trace log of first testrun

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-backend#34]
Analyze tracelog of firt testrun of JamFactory

https://gist.github.com/exp625/865b2d29fde7b9d31e463a80f93c2874

**Comment by exp625** [comment]
Crash was caused by someone trying to create a new JamSession

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6fd259]

goroutine 80 [running]:
github.com/jamfactoryapp/jamfactory-backend/models.(*JamSession).Conductor(0xc0000b30e0)
        /go/src/github.com/jamfactoryapp/jamfactory-backend/models/jamsession.go:85 +0x1f9
created by github.com/jamfactoryapp/jamfactory-backend/controllers.GenerateNewJamSession
        /go/src/github.com/jamfactoryapp/jamfactory-backend/controllers/jamfactory.go:25 +0xe3
```

**Comment by exp625** [comment]
Hopefully fixed by refactoring.
